# Generated by Django 5.0.6 on 2024-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmlog",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
