# Generated by Django 5.0.6 on 2024-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmlog", "0002_farmlog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmlog",
            name="title",
            field=models.CharField(default="Default Title", max_length=100),
        ),
    ]
